#!/usr/bin/env python
"""A shell script for copying of a file's full path into the clipboard.
Currently supports OSX and Linux."""

import sys
import os

def copy_string_to_clipboard(s):
    import subprocess
    if sys.platform == 'darwin':
        subp = subprocess.Popen(['pbcopy'], stdin=subprocess.PIPE)
        subp.communicate(s)
    elif sys.platform == 'linux':
        p = subprocess.Popen(['xclip'], stdin=subprocess.PIPE)
        p.communicate(s)
    else:
        raise NotImplementedError('Only OSX and Linux are currently supported')


def main():
    if len(sys.argv) == 1:
        fullpath = os.getcwd()
    elif len(sys.argv) == 2:
        fullpath = os.path.abspath(sys.argv[1])
    else:
        print('Usage: fn <path-to-filename>')
        print('This will copy the full path of a given file name to the OSX clipboard.')
        print('If no path is given, the current directory will be copied.')
        return

    print(fullpath)
    copy_string_to_clipboard(fullpath.encode('utf-8'))


if __name__ == '__main__':
    main()

